name: Pytest

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      # Do not run if only the documentation has been changed
      - 'docs/**'
      - '**/*.md'
  pull_request:
    paths-ignore:
      # Do not run if only the documentation has been changed
      - 'docs/**'
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        
    - name: Analysing the code with pytest
      run: |
        pytest 
